# Generated by Django 2.1.2 on 2018-10-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barrier_field', '0003_auto_20181025_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
